theme: jekyll-theme-dinky
title: Victor Mora - Data Analysis & Data Visualization
description: A Collection of Notes & Projects on Data Analysis & Data Visualization
permalink: /blog/:year/:month/:day/:title
